new_list = ["hello", "python"]
print(new_list)
print(id(new_list))
new_list.extend("super_python")
print(new_list)
str1 = "| |".join(new_list)
print(str1)
new_str1 = str1.split()
print(new_str1)
new_str1.remove("|p|")
print(new_str1)
popped_element = new_str1.pop(1)
print(popped_element)
print(new_str1)